In [21]:
import pandas as pd
import numpy as np

df = pd.read_excel("OnlineRetail.xlsx")

#print(df.head())

#print(df.shape)


print(df.isnull().sum())

print("duplicate rows", df.duplicated().sum())

print(df.describe())

missing_values = df.isnull().sum()

print(missing_values)

percen = ((df.isnull().sum())/len(df))*100

print(percen.astype(str) + "%")


# Step 4: Count unusual numerical values

print("Negative quantities:",
      (df["Quantity"] < 0).sum())

print("Zero quantities:",
      (df["Quantity"] == 0).sum())

print("Zero prices:",
      (df["UnitPrice"] == 0).sum())

print("Negative prices:",
      (df["UnitPrice"] < 0).sum())

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
duplicate rows 5268
            Quantity                    InvoiceDate      UnitPrice  \
count  541909.000000                         541909  541909.000000
mean        9.552250  2011-07-04 13:34:57.156386048       4.611114
min    -80995.000000            2010-12-01 08:26:00  -11062.060000
25%         1.000000            2011-03-28 11:34:00       1.250000
50%         3.000000            2011-07-19 17:17:00       2.080000
75%        10.000000            2011-10-19 11:27:00       4.130000
max     80995.000000            2011-12-09 12:50:00   38970.000000
std       218.081158                            NaN      96.759853

          CustomerID
count  406829.000000
mean    15287.690570
min     12346.000000
25%     13953.000000
50%     15152.000000
75%     16791.000000
max     18287.000000
std      1713.600303
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64
InvoiceNo                     0.0%
StockCode                     0.0%
Description    0.2683107311375157%
Quantity                      0.0%
InvoiceDate                   0.0%
UnitPrice                     0.0%
CustomerID     24.926694334288598%
Country                       0.0%
dtype: object
Negative quantities: 10624
Zero quantities: 0
Zero prices: 2515
Negative prices: 2

In [25]:

# Step 5: Create a summary of data quality issues

audit_summary = pd.DataFrame({
    "Issue": [
        "Total rows",
        "Total columns",
        "Missing CustomerID",
        "Missing Description",
        "Duplicate rows",
        "Negative quantities",
        "Zero prices",
        "Negative prices"
    ],
    "Count": [
        len(df),
        len(df.columns),
        df["CustomerID"].isnull().sum(),
        df["Description"].isnull().sum(),
        df.duplicated().sum(),
        (df["Quantity"] < 0).sum(),
        (df["UnitPrice"] == 0).sum(),
        (df["UnitPrice"] < 0).sum()
    ]
})

audit_summary

print(percen.astype(str) + "%")

InvoiceNo                     0.0%
StockCode                     0.0%
Description    0.2683107311375157%
Quantity                      0.0%
InvoiceDate                   0.0%
UnitPrice                     0.0%
CustomerID     24.926694334288598%
Country                       0.0%
dtype: object

In [26]:

# Create a copy of the original dataset
df_clean = df.copy()

# Check the number of rows and columns
print("Original dataset shape:", df.shape)
print("Working dataset shape:", df_clean.shape)

Original dataset shape: (541909, 8)
Working dataset shape: (541909, 8)

In [27]:

# Count duplicates before removal
duplicates_before = df_clean.duplicated().sum()

# Remove duplicate rows
df_clean = df_clean.drop_duplicates()

# Count duplicates after removal
duplicates_after = df_clean.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates after cleaning:", duplicates_after)
print("Shape after removing duplicates:", df_clean.shape)

Duplicates before cleaning: 5268
Duplicates after cleaning: 0
Shape after removing duplicates: (536641, 8)

In [28]:

# Select rows where Description is missing
missing_description_rows = df_clean[
    df_clean["Description"].isnull()
]

print("Rows with missing Description:",
      len(missing_description_rows))

missing_description_rows.head(10)

Rows with missing Description: 1454

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [33]:
missing_description_rows.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [37]:
display(df_clean.shape)
missing_description_rows.head(10)

(536641, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [38]:

# Select rows where Description is missing
missing_desc = df_clean[
    df_clean["Description"].isnull()
]

# Count how many have zero prices
zero_price_missing_desc = (
    missing_desc["UnitPrice"] == 0
).sum()

# Count how many have non-zero prices
nonzero_price_missing_desc = (
    missing_desc["UnitPrice"] != 0
).sum()

print("Missing descriptions:", len(missing_desc))
print("With zero prices:", zero_price_missing_desc)
print("With non-zero prices:", nonzero_price_missing_desc)

Missing descriptions: 1454
With zero prices: 1454
With non-zero prices: 0

In [39]:

# Count missing descriptions with negative quantities
negative_quantity_missing_desc = (
    missing_desc["Quantity"] < 0
).sum()

# Count missing descriptions with positive quantities
positive_quantity_missing_desc = (
    missing_desc["Quantity"] > 0
).sum()

print("Negative quantities:", negative_quantity_missing_desc)
print("Positive quantities:", positive_quantity_missing_desc)

Negative quantities: 862
Positive quantities: 592

In [40]:

# Check whether missing-description rows are cancellations

missing_desc = df_clean[
    df_clean["Description"].isnull()
]

cancelled_missing_desc = missing_desc[
    missing_desc["InvoiceNo"].astype(str).str.startswith("C")
]

print("Missing descriptions:", len(missing_desc))
print("Missing descriptions with cancelled invoices:",
      len(cancelled_missing_desc))

cancelled_missing_desc.head(10)

Missing descriptions: 1454
Missing descriptions with cancelled invoices: 0

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [41]:

# Identify cancelled invoices
cancelled_rows = df_clean[
    df_clean["InvoiceNo"].astype(str).str.startswith("C")
]

print("Cancelled transaction rows:", len(cancelled_rows))

cancelled_rows.head(10)

Cancelled transaction rows: 9251

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [42]:

# Inspect the quantities in cancelled transactions

print("Negative quantities:",
      (cancelled_rows["Quantity"] < 0).sum())

print("Zero quantities:",
      (cancelled_rows["Quantity"] == 0).sum())

print("Positive quantities:",
      (cancelled_rows["Quantity"] > 0).sum())

Negative quantities: 9251
Zero quantities: 0
Positive quantities: 0

In [43]:


# Check unusual quantities and prices

print("Negative quantities:",
      (df_clean["Quantity"] < 0).sum())

print("Zero quantities:",
      (df_clean["Quantity"] == 0).sum())

print("Negative prices:",
      (df_clean["UnitPrice"] < 0).sum())

print("Zero prices:",
      (df_clean["UnitPrice"] == 0).sum())

Negative quantities: 10587
Zero quantities: 0
Negative prices: 2
Zero prices: 2510

In [44]:

# Display records with negative unit prices

negative_price_rows = df_clean[
    df_clean["UnitPrice"] < 0
]

negative_price_rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [47]:

# Identify negative-price records
negative_price_rows = df_clean[
    df_clean["UnitPrice"] < 0
]

print("Negative-price records:", len(negative_price_rows))
print(negative_price_rows[
    ["InvoiceNo", "Description", "Quantity", "UnitPrice"]
])

Negative-price records: 2
       InvoiceNo      Description  Quantity  UnitPrice
299983   A563186  Adjust bad debt         1  -11062.06
299984   A563187  Adjust bad debt         1  -11062.06

In [48]:

# Create the cleaned master dataset
# Exact duplicate rows were already removed

df_master_clean = df_clean.copy()

print("Original rows:", len(df))
print("Rows after duplicate removal:", len(df_master_clean))
print("Remaining duplicates:",
      df_master_clean.duplicated().sum())

Original rows: 541909
Rows after duplicate removal: 536641
Remaining duplicates: 0

In [50]:

# Step 1: Exclude cancelled invoices
sales_df = df_master_clean[
    ~df_master_clean["InvoiceNo"].astype(str).str.startswith("C")
].copy()

# Step 2: Remove records without product descriptions
sales_df = sales_df[
    sales_df["Description"].notna()
].copy()

# Step 3: Keep positive quantities
sales_df = sales_df[
    sales_df["Quantity"] > 0
].copy()

# Step 4: Keep positive unit prices
sales_df = sales_df[
    sales_df["UnitPrice"] > 0
].copy()

# Step 5: Check the result
print("Rows for product-sales analysis:", len(sales_df))
print("Columns:", len(sales_df.columns))

print("Missing descriptions:",
      sales_df["Description"].isnull().sum())

print("Non-positive quantities:",
      (sales_df["Quantity"] <= 0).sum())

print("Non-positive prices:",
      (sales_df["UnitPrice"] <= 0).sum())

print("Duplicate rows:", sales_df.duplicated().sum())

Rows for product-sales analysis: 524878
Columns: 8
Missing descriptions: 0
Non-positive quantities: 0
Non-positive prices: 0
Duplicate rows: 0

In [51]:

# Create a before-and-after data quality report

quality_report = pd.DataFrame({
    "Metric": [
        "Total rows",
        "Duplicate rows",
        "Missing CustomerID",
        "Missing Description",
        "Negative quantities",
        "Zero prices",
        "Negative prices"
    ],

    "Original Dataset": [
        len(df),
        df.duplicated().sum(),
        df["CustomerID"].isnull().sum(),
        df["Description"].isnull().sum(),
        (df["Quantity"] < 0).sum(),
        (df["UnitPrice"] == 0).sum(),
        (df["UnitPrice"] < 0).sum()
    ],

    "Cleaned Master Dataset": [
        len(df_master_clean),
        df_master_clean.duplicated().sum(),
        df_master_clean["CustomerID"].isnull().sum(),
        df_master_clean["Description"].isnull().sum(),
        (df_master_clean["Quantity"] < 0).sum(),
        (df_master_clean["UnitPrice"] == 0).sum(),
        (df_master_clean["UnitPrice"] < 0).sum()
    ],

    "Product Sales Dataset": [
        len(sales_df),
        sales_df.duplicated().sum(),
        sales_df["CustomerID"].isnull().sum(),
        sales_df["Description"].isnull().sum(),
        (sales_df["Quantity"] < 0).sum(),
        (sales_df["UnitPrice"] == 0).sum(),
        (sales_df["UnitPrice"] < 0).sum()
    ]
})

quality_report

,Metric,Original Dataset,Cleaned Master Dataset,Product Sales Dataset
0,Total rows,541909,536641,524878
1,Duplicate rows,5268,0,0
2,Missing CustomerID,135080,135037,132186
3,Missing Description,1454,1454,0
4,Negative quantities,10624,10587,0
5,Zero prices,2515,2510,0
6,Negative prices,2,2,0

In [52]:

# Create a sales value column

sales_df["SalesValue"] = (
    sales_df["Quantity"] * sales_df["UnitPrice"]
)

# Display sample results
sales_df[
    ["InvoiceNo", "Description", "Quantity",
     "UnitPrice", "SalesValue"]
].head(10)

,InvoiceNo,Description,Quantity,UnitPrice,SalesValue
0,536365,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,15.30
1,536365,WHITE METAL LANTERN,6,3.39,20.34
2,536365,CREAM CUPID HEARTS COAT HANGER,8,2.75,22.00
3,536365,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,20.34
4,536365,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,20.34
5,536365,SET 7 BABUSHKA NESTING BOXES,2,7.65,15.30
6,536365,GLASS STAR FROSTED T-LIGHT HOLDER,6,4.25,25.50
7,536366,HAND WARMER UNION JACK,6,1.85,11.10
8,536366,HAND WARMER RED POLKA DOT,6,1.85,11.10
9,536367,ASSORTED COLOUR BIRD ORNAMENT,32,1.69,54.08

In [53]:

# Export the datasets and quality report

df_master_clean.to_csv(
    "retail_cleaned_master.csv", index=False
)

sales_df.to_csv(
    "retail_product_sales.csv", index=False
)

quality_report.to_csv(
    "data_quality_report.csv", index=False
)

print("Project files exported successfully.")

Project files exported successfully.

In [54]:

import zipfile

with zipfile.ZipFile(
    "retail_data_cleaning_outputs.zip", "w"
) as zip_file:

    zip_file.write(
        "retail_cleaned_master.csv"
    )

    zip_file.write(
        "retail_product_sales.csv"
    )

    zip_file.write(
        "data_quality_report.csv"
    )

print("ZIP file created successfully.")

ZIP file created successfully.

In [55]:
from google.colab import files

files.download("retail_data_cleaning_outputs.zip")

In [49]:

# Exclude cancelled invoices
sales_df = df_master_clean[
    ~df_master_clean["InvoiceNo"].astype(str).str.startswith("C")
].copy()

# Keep only records with a product description
sales_df = sales_df[
    sales_df["Description"].notna()
].copy()

# Keep positive quantities
sales_df = sales_df[
    sales_df["Quantity"] > 0
].copy()

# Keep positive unit prices
sales_df = sales_df[
    sales_df["UnitPrice"] > 0
].copy()

print("Rows for ordinary product-sales analysis:",
      len(sales_df))

print("Remaining missing descriptions:",
      sales_df["Description"].isnull().sum())

print("Remaining non-positive quantities:",
      (sales_df["Quantity"] <= 0).sum())

print("Remaining non-positive prices:",
      (sales_df["UnitPrice"] <= 0).sum())

Rows for ordinary product-sales analysis: 524878
Remaining missing descriptions: 0
Remaining non-positive quantities: 0
Remaining non-positive prices: 0

In [45]:

# Display records with zero quantities

zero_quantity_rows = df_clean[
    df_clean["Quantity"] == 0
]

print("Number of zero-quantity rows:",
      len(zero_quantity_rows))

zero_quantity_rows.head()

Number of zero-quantity rows: 0

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [46]:

# Display records with zero quantities

zero_quantity_rows = df_clean[
    df_clean["Quantity"] == 0
]

print("Number of zero-quantity rows:",
      len(zero_quantity_rows))

zero_quantity_rows.head()

Number of zero-quantity rows: 0

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []